---

- name: Enabled IPs and OSPF routing 
  hosts: 
    - hosts_phase_1
    - hosts_phase_2
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Interfaces status enabled
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.interface }}"
            description: "{{ item.desc }}"
            enabled: "{{ item.enabled }}"
            mode: "{{ item.mode | default(omit) }}"
      loop: "{{ interfaces }}"

    - name: Address L3 interfaces config 
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ item.interface }}"
            ipv4:
              - address: "{{ item.ip }} {{ item.mask }}"
      loop: "{{ interfaces }}"

    - name: OSPF interfaces config
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: "{{ item.interface }}"
            address_family:
              - afi: ipv4
                process:
                  id: 1
                  area_id: "{{ item.area }}"
                network:
                  point_to_point: "{{ true if item.passive == false else omit }}"
      loop: "{{ interfaces }}"

    - name: OSPF process config 
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - router_id: "{{ router_id }}"
              process_id: 1
              passive_interfaces:
                interface:
                  set_interface: true
                  name: "{{ interfaces | selectattr('passive', 'equalto', true) | map(attribute='interface') | list }}"
      when: "{{ interfaces | selectattr('passive', 'equalto', true) | list | length > 0 }}"

