all_hosts:
  children:
    hosts_phase_1:
      hosts:
        RB-1:
          ansible_host: 10.75.246.122
        RA-1:
          ansible_host: 10.103.162.106
        RD-1:
          ansible_host: 10.204.40.2
        RC-1:
          ansible_host: 10.105.29.90
    hosts_phase_2:
      hosts:
        RD-2:
          ansible_host: 10.238.58.126
        SA-1:
          ansible_host: 10.170.131.194
        RC-2:
          ansible_host: 10.252.147.206
        RF-1:
          ansible_host: 10.20.20.2
        RA-3:
          ansible_host: 10.20.10.2
        RA-1-SWC-1:
          ansible_host: 10.104.10.2


  vars:
    ansible_network_os: ios
    ansible_connection: network_cli
    ansible_user: ccna
    ansible_ssh_pass: '1234'
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: '1234'


